name: Compilar y subir 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - id: release
      uses: rymndhng/release-on-push-action@master
      with:
        bump_version_scheme: minor
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Compilando...
      run: ./gradlew build --x test
    
    
    - name: Creando imagen de docker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ezequiel2point0/edm-server
        tags: ${{ steps.release.outputs.version }},latest
